### ISSUE TITLE
Mayor balance

### ISSUE THREAD

**Issue by Dukenukem117** [DaneelTrevize/Modded-Mayors#1]
Thanks for reviving this but how hard is it to modify the mayors myself? Some of them are not really viable at all.

**Comment by DaneelTrevize** [comment]
Use the posted password to extract the game's ZXRules.dat file as a decrypted version.

Use a text editor to change the XML inside. You may first want to test simply replacing the Mayors section with the versioned unmodified or modified snippet, to test your workflow.

Repack & encrypt into a new ZXRules.dat file using the same password. 7-Zip settings are in the Readme.

----

As for which specific XML changes you can make that are compatible, review the original and supplied modified snippets, as well as some of the extracted data table spreadsheets, and then it's trial & error. There is no collected list of available variables/attributes which TAB accepts. Using the official map editor & docs of supported scripting may help in this regard.

**Comment by Soanfirewak** [comment]
So you cannot add your own Variables/Objects/... even with this form of modding/editing?

**Comment by DaneelTrevize** [comment]
These modification of the game's packed data tables do not change how the game engine functions, thus cannot add new attributes/variables.

If by objects you mean new entries in the tech/unit tree, it is not clear what about the number and IDs of those is hard-coded into the engine. For now you can appropriate an entry, such as Lucifers, and change their name, weapon stats, tech requirements, etc.

To change their audio and visual assets, people have already released TAB audio and font mods, a few have dabbled with [altering texture files](https://www.reddit.com/r/TheyAreBillions/comments/bnd1pd/11_custom_map_themes_tutorial/), but for units there is [the challenge to find the format/algorithm](https://www.reddit.com/r/TheyAreBillions/comments/gxnlwf/modded_reskin/) that encodes [individual frames into a larger single texture](https://i.imgur.com/RjNp8MB.jpg). If someone can work on the tooling to explore and even solve this problem, then there'll be much more interest and effort spent on pushing the hardcoded limits of number of defined techs, weapons, units, etc.

**Comment by Warlock314** [comment]
There are some unused entries (with number & ID) in the tech/unit tree. I played around a bit with them. They kind of worked, but were missing some graphics. I might play around some more with them when I have access to my computer again.

**Comment by DaneelTrevize** [comment]
The [v1.1 offical game editor has many more scripting features](https://store.steampowered.com/news/app/644930/view/2939123552821183913), offering many more options on a per custom game basis (and still working with randomly generated maps) rather than needing to mod all game behaviour via the rules file.
