### ISSUE TITLE
tinny update mayors

### ISSUE THREAD

**Issue by halk6000** [DaneelTrevize/Modded-Mayors#4]
hmm if you can add Optional 4 mayors . always but randomly.
1 - supply  add your bonus too Build building or send resourcs 
2 - Reformer add your bonus any building or Army
3 - Manager Military can you get bonus military or always get random updating for defence building or get bonus to place traps or towers.
4 - all in 1  - so all efect form one.  
if this funcion need any language remove i can help you make this mod for polish. ;)

**Comment by DaneelTrevize** [comment]
The chief purpose of this repo is to demonstrate that with the published password and procedure, people can fork and create their own modded mayors/rules version.

Those specific ideas might be best implemented using the latest addition to the official scriptable game aspects using the 1st party editor. Custom maps such as Return by nonomo4 demonstrate the available options.
