### ISSUE TITLE
password for the latest game release

### ISSUE THREAD

**Issue by Al-git-gork** [DaneelTrevize/Modded-Mayors#5]
Hi

Hope i dont come across as demanding.

Just want to ask if you know the password for the latest version or how to extract it.

**Comment by DaneelTrevize** [comment]
It seems the game version is still 1.1.3, so the following from 17th March should be applicable.

https://github.com/DaneelTrevize/Modded-Mayors/commit/98001deca153a8857b37a0fa35ad59005788f191

**Comment by DaneelTrevize** [comment]
Update: The password was valid since then, but the Release hadn't been updated until today, with 8f7f1af.
